### ISSUE TITLE
Mark a string as translatable but don't translate it right away

### ISSUE THREAD

**Issue by bart-1990** [Polyconseil/vue-gettext#46]
I'm using vue-gettext but I'm encountering the following problem:

Let's say I have a list of animals. I add a 'tiger' using the following code:
```
this.animals.push(this.$gettext('tiger'));
```
This way I make sure the message with the id 'tiger' will be added to my .pot file. However if I would start up my app in French and if I would change the language of my app to English, the list of animals would not be translated. After all my list contains the French string for 'tiger', which cannot be translated back to English using $getttext() or <translate> because there is no message id with the French word for tiger in the .pot file (and thus not in the translations JSON file).

Is it possible to mark a string as translatable so it will be added to the .pot file when running the makefile command, but without translating it in your app right away?

**Comment by kemar** [comment]
When you do:

```javascript
this.animals.push(this.$gettext('tiger'));
```

what you're really doing is this (assuming that French is the current language):

```javascript
this.animals.push('Tigre');
```

There is no way for the content of your array to be translated again afterwards, because the content of your array is a simple string i.e. `this.$gettext('tiger'))` returns a `string`.

Even iy you had the message id for the French word, it wouldn't be translated.

If what you want is to translate the content of an array you could use a `computed` property, e.g.:

```javascript
computed: {
  animals () {
    return [
        this.$gettext('Tiger'),
        this.$gettext('Dog'),
        this.$gettext('Cat'),
    ]
  },
},
```

Then in your template

```html
<ul>
  <li v-for='animal in animals'>{{ animal }}</li>
</ul>
```
