### ISSUE TITLE
How to interpolate router-link?

### ISSUE THREAD

**Issue by chlab** [Polyconseil/vue-gettext#48]
What's the best way to translate something like this?

```
<span class="checkbox-text" v-translate>I agree to the <router-link :to="{ name: 'TermsAndConditions' }">terms and conditions</router-link></span>
```

At runtime, the router-link is resolved to a regular link and vue-gettext can't find the corresponding translation.

The only other way that comes to mind is to make the entire link a placeholder and add a computed property that returns the html for the link, like:

```
<span class="checkbox-text" v-translate :v-translate-params="{ termsLink }">
  I agree to the %{termsLink}
</span>
```

then do something like:

```
termsLink () {
    const route = this.$router.resolve({ name: 'TermsAndConditions' }, this.$route)
    const linkText = this.$gettext('terms and conditions')
    return `<a href="${route.location.path}">${linkText}</a>`
  }
```

With this method ^ I get the following warning in the console:

```
No expression is provided for change detection. The translation for this key will be static
```

**Comment by kemar** [comment]
Yes, this is a good way to translate a `router-link`. Can't think of anything better.

Don't worry about the console info message, you won't see it in production because the [`silent` configuration option](https://github.com/Polyconseil/vue-gettext#configuration) will mostly be set to [`false`](https://vuejs.org/v2/api/#silent) (look [here](https://github.com/Polyconseil/vue-gettext/blob/4004bda2097c8635dd3259e2d29708e670035b64/src/directive.js#L79)).

This info message is just a reminder for [this caveat](https://github.com/Polyconseil/vue-gettext#caveat-when-using-v-translate-with-interpolation).

**Comment by chlab** [comment]
Ok thanks for your response!

**Comment by mitar** [comment]
But rendering `<a>` link in this way instead of `router-link` means that click does not get intercepted in the history mode, so the app reloads?

**Comment by rmelchner** [comment]
Maybe another approach is possible in this case. You could split the Text and add the router link in between.
`<span>
    {{splitedText[0]}}
        <router-link :to="`privacy`" target="_blank">linktext</router-link>
    {{splitedText[1]}}
</span>`
`computed: {
    splitedText() {
      this.myResult = customtext.split('%{termsLink}');
      return this.myResult;
    }
},
`

**Comment by mitar** [comment]
But this is then hard to translate. Not all languages would split in the same way. So translator would have to translate three fragments (text before link, link text, and text after link) as one. Very confusing.
