### ISSUE TITLE
Reactivity problem when using v-translate in combination with v-if (since 2.1.0)

### ISSUE THREAD

**Issue by Nivani** [Polyconseil/vue-gettext#79]
When using v-translate in combination with v-if, reactivity is lost.

This jsfiddle demonstrates the problem:
http://jsfiddle.net/eywraw8t/429637/

When clicking the buttons at the top you will see that the bottom label (that uses v-translate) is not reactive.

Lowering the version of vue-gettext to 2.0.31 fixes the problem: http://jsfiddle.net/eywraw8t/429660/

**Comment by kemar** [comment]
Yes, this is how the plugin works since [v2.1.0](https://github.com/Polyconseil/vue-gettext/releases/tag/v2.1.0).

It's up to the developper to add a `key` attribute manually for such cases. You can read about [Vue rendering mechanism here](https://vuejs.org/v2/guide/conditional.html#Controlling-Reusable-Elements-with-key).

You can also tell the plugin to generate `key` attributes automatically by enabling the `autoAddKeyAttributes` config option introduced in [v2.1.0](https://github.com/Polyconseil/vue-gettext/releases/tag/v2.1.0), but it can lead to another set of problems.

See issues #29 and #66 for the full history.

**Comment by Nivani** [comment]
Aha, you're right. Didn't search the issues thoroughly enough
